# Generated by Django 5.0.6 on 2026-06-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Meetup', 'Meetup'), ('Bootcamp', 'Bootcamp'), ('Conference', 'Conference'), ('Training', 'Training'), ('Workshop', 'Workshop')], max_length=20)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('speaker', models.CharField(blank=True, default='', max_length=255)),
                ('prize', models.CharField(blank=True, default='', max_length=100)),
                ('seats', models.IntegerField(default=50)),
                ('registered_count', models.IntegerField(default=0)),
                ('accent', models.CharField(choices=[('cyan', 'Cyan'), ('violet', 'Violet'), ('emerald', 'Emerald')], default='cyan', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('past', 'Past'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
