# Generated by Django 5.0.4 on 2026-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tech Park', 'Tech Park'), ('Government', 'Government'), ('Corporate', 'Corporate'), ('University', 'University'), ('Accelerator', 'Accelerator'), ('International', 'International'), ('Association', 'Association')], max_length=50)),
                ('tier', models.CharField(choices=[('strategic', 'Strategic'), ('global', 'Global'), ('regional', 'Regional')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, upload_to='partners/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
    ]
