# Generated by Django 5.0.6 on 2026-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.CharField(blank=True, default='', help_text='Logo URL or path', max_length=500),
        ),
    ]
