# Generated by Django 5.0.4 on 2026-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('Idea', 'Idea'), ('Pre-Seed', 'Pre-Seed'), ('Seed', 'Seed'), ('Series A', 'Series A')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('founder_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('team_size', models.IntegerField(default=1)),
                ('funding_needed', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Startup Application',
                'verbose_name_plural': 'Startup Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
