# Generated by Django 5.0.6 on 2026-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_announcement_image_alter_job_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('contact', 'Contact'), ('investor', 'Investor'), ('startup', 'Startup')], default='contact', max_length=20),
        ),
    ]
