# Generated by Django 5.0.6 on 2026-06-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='developer_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
