# Generated by Django 5.0.6 on 2026-06-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_startup_developer_images_startup_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='news',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
