# Generated by Django 5.0.6 on 2026-06-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('mentor', 'Mentor')], default='student', max_length=20)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('course', models.CharField(blank=True, default='', max_length=255)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('projects_count', models.IntegerField(default=0)),
                ('certificates_count', models.IntegerField(default=0)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('accent', models.CharField(choices=[('cyan', 'Cyan'), ('violet', 'Violet'), ('emerald', 'Emerald')], default='cyan', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-score', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('category', models.CharField(default='general', max_length=100)),
                ('icon', models.CharField(blank=True, default='🏆', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-date'],
            },
        ),
    ]
