# Generated by Django 5.0.4 on 2026-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('tech_stack', models.TextField(help_text='Comma-separated list of technologies')),
                ('accent', models.CharField(default='accent', max_length=20)),
                ('primary_metric_label', models.CharField(max_length=255)),
                ('primary_metric_value', models.CharField(max_length=50)),
                ('secondary_metric_label', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_metric_value', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Homepage Startup',
                'verbose_name_plural': 'Homepage Startups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('accent', models.CharField(choices=[('accent', 'Accent'), ('violet', 'Violet'), ('emerald', 'Emerald')], default='accent', max_length=20)),
                ('icon_name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructure',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perk',
                'verbose_name_plural': 'Perks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
    ]
