# Generated by Django 5.0.6 on 2026-06-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProxy',
        ),
    ]
