# Generated by Django 5.0.4 on 2026-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('investor_type', models.CharField(choices=[('VC Fund', 'VC Fund'), ('Corporate VC', 'Corporate VC'), ('Accelerator', 'Accelerator'), ('Development VC', 'Development VC'), ('Corporate', 'Corporate'), ('Strategic', 'Strategic'), ('Development', 'Development'), ('Angel', 'Angel')], max_length=50)),
                ('ticket_size', models.CharField(blank=True, default='', max_length=100)),
                ('sectors', models.TextField(blank=True, default='', help_text='Comma-separated list of sectors')),
                ('status', models.CharField(choices=[('active', 'Active'), ('negotiation', 'Negotiation'), ('due_diligence', 'Due Diligence'), ('closed', 'Closed')], default='active', max_length=30)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['-created_at'],
            },
        ),
    ]
