from django.urls import path
from . import views

urlpatterns = [
    path("stats/", views.StatViewSet.as_view({"get": "list"}), name="stats-list"),
    path("partners/", views.PartnerViewSet.as_view({"get": "list"}), name="partners-list"),
    path("hero-video/", views.HeroVideoViewSet.as_view({"get": "list"}), name="hero-video-list"),
    path("news/", views.NewsViewSet.as_view({"get": "list"}), name="news-list"),
    path("news/<int:pk>/", views.NewsViewSet.as_view({"get": "retrieve"}), name="news-detail"),
    path("announcements/", views.AnnouncementViewSet.as_view({"get": "list"}), name="announcements-list"),
    path("announcements/<int:pk>/", views.AnnouncementViewSet.as_view({"get": "retrieve"}), name="announcements-detail"),
    path("startups/", views.StartupViewSet.as_view({"get": "list"}), name="startups-list"),
    path("startups/<int:pk>/", views.StartupViewSet.as_view({"get": "retrieve"}), name="startups-detail"),
    path("jobs/", views.JobViewSet.as_view({"get": "list"}), name="jobs-list"),
    path("jobs/<int:pk>/", views.JobViewSet.as_view({"get": "retrieve"}), name="jobs-detail"),
    path("leads/", views.LeadCreateView.as_view(), name="leads-create"),
    path("admin/stats/", views.AdminStatViewSet.as_view({"get": "list", "post": "create"}), name="admin-stats-list"),
    path("admin/stats/<int:pk>/", views.AdminStatViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-stats-detail"),
    path("admin/partners/", views.AdminPartnerViewSet.as_view({"get": "list", "post": "create"}), name="admin-partners-list"),
    path("admin/partners/<int:pk>/", views.AdminPartnerViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-partners-detail"),
    path("admin/hero-video/", views.AdminHeroVideoViewSet.as_view({"get": "list", "post": "create"}), name="admin-hero-video-list"),
    path("admin/hero-video/<int:pk>/", views.AdminHeroVideoViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-hero-video-detail"),
    path("admin/news/", views.AdminNewsViewSet.as_view({"get": "list", "post": "create"}), name="admin-news-list"),
    path("admin/news/<int:pk>/", views.AdminNewsViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-news-detail"),
    path("admin/announcements/", views.AdminAnnouncementViewSet.as_view({"get": "list", "post": "create"}), name="admin-announcements-list"),
    path("admin/announcements/<int:pk>/", views.AdminAnnouncementViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-announcements-detail"),
    path("admin/startups/", views.AdminStartupViewSet.as_view({"get": "list", "post": "create"}), name="admin-startups-list"),
    path("admin/startups/<int:pk>/", views.AdminStartupViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-startups-detail"),
    path("admin/jobs/", views.AdminJobViewSet.as_view({"get": "list", "post": "create"}), name="admin-jobs-list"),
    path("admin/jobs/<int:pk>/", views.AdminJobViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"}), name="admin-jobs-detail"),
    path("admin/leads/", views.AdminLeadViewSet.as_view({"get": "list"}), name="admin-leads-list"),
    path("admin/leads/<int:pk>/", views.AdminLeadViewSet.as_view({"get": "retrieve", "delete": "destroy"}), name="admin-leads-detail"),
]
