# Generated by Django 5.0.6 on 2026-06-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('space_type', models.CharField(choices=[('desk', 'Desk'), ('meeting_room', 'Meeting Room'), ('private_office', 'Private Office'), ('lab', 'Lab'), ('conference_hall', 'Conference Hall')], max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('price_per_hour', models.IntegerField(default=0)),
                ('price_per_day', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('accent', models.CharField(choices=[('cyan', 'Cyan'), ('violet', 'Violet'), ('emerald', 'Emerald')], default='cyan', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coworking Space',
                'verbose_name_plural': 'Coworking Spaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='coworking.coworkingspace')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
